/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Augusto Pamplona
 */
public class AvaliarGrupo extends javax.swing.JFrame {

    /** Creates new form AvaliarGrupo */
    public AvaliarGrupo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jtNotaAvaliacao = new javax.swing.JTextField();
        jbOkAvaliacao = new javax.swing.JButton();
        jbCancelarAvaliacao = new javax.swing.JButton();
        jcbGruposAvaliacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Avaliar grupo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, 369, 190));

        jLabel2.setText("Nota:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        jtNotaAvaliacao.setText("NOTA");
        jtNotaAvaliacao.setToolTipText("");
        getContentPane().add(jtNotaAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 247, -1, -1));

        jbOkAvaliacao.setText("Ok");
        jbOkAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkAvaliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbOkAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 278, 73, -1));

        jbCancelarAvaliacao.setText("Cancelar");
        getContentPane().add(jbCancelarAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 278, -1, -1));

        jcbGruposAvaliacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo 1", "Grupo 2", "Grupo 3", "Grupo 4" }));
        jcbGruposAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGruposAvaliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbGruposAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbOkAvaliacaoActionPerformed

    private void jcbGruposAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGruposAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGruposAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelarAvaliacao;
    private javax.swing.JButton jbOkAvaliacao;
    private javax.swing.JComboBox<String> jcbGruposAvaliacao;
    private javax.swing.JTextField jtNotaAvaliacao;
    // End of variables declaration//GEN-END:variables

}
