/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Augusto Pamplona
 */
public class SolicitarParticipacaoGrupo extends javax.swing.JFrame {

    /** Creates new form SolicitarParticipacaoGrupo */
    public SolicitarParticipacaoGrupo() {
        initComponents();
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbEscolherGrupo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbEnviarSolicitacao = new javax.swing.JButton();
        jbCancelarSolicitacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Solicitar participação em um grupo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("Escolha o grupo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        jcbEscolherGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbEscolherGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEscolherGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbEscolherGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 41, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 272, -1));

        jbEnviarSolicitacao.setText("Enviar");
        jbEnviarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarSolicitacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbEnviarSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 168, 73, -1));

        jbCancelarSolicitacao.setText("Cancelar");
        jbCancelarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarSolicitacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelarSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 168, 73, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbEscolherGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEscolherGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEscolherGrupoActionPerformed

    private void jbEnviarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarSolicitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEnviarSolicitacaoActionPerformed

    private void jbCancelarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarSolicitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarSolicitacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitarParticipacaoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitarParticipacaoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitarParticipacaoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitarParticipacaoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitarParticipacaoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelarSolicitacao;
    private javax.swing.JButton jbEnviarSolicitacao;
    private javax.swing.JComboBox<String> jcbEscolherGrupo;
    // End of variables declaration//GEN-END:variables

}
