/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControladorGrupo;
import dao.GrupoDao;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Grupo;

/**
 *
 * @author Augusto Pamplona
 */
public class TelaCriarGrupo extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriarGrupo
     */
    public TelaCriarGrupo() {
        initComponents();
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTituloGrupo = new javax.swing.JTextField();
        jbCriarGrupo = new javax.swing.JButton();
        jbCancelarCriacaoGrupo = new javax.swing.JButton();
        jbConvidarTelaCriarGrupo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listGruposExistentes = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Criar grupo");

        jLabel2.setText("Título:");

        tfTituloGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTituloGrupoActionPerformed(evt);
            }
        });

        jbCriarGrupo.setText("Criar");
        jbCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarGrupoActionPerformed(evt);
            }
        });

        jbCancelarCriacaoGrupo.setText("Cancelar");
        jbCancelarCriacaoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarCriacaoGrupoActionPerformed(evt);
            }
        });

        jbConvidarTelaCriarGrupo.setText("Convidar");

        jLabel3.setText("Grupos existentes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listGruposExistentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfTituloGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCriarGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(jbCancelarCriacaoGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(jbConvidarTelaCriarGrupo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTituloGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listGruposExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCriarGrupo)
                    .addComponent(jbCancelarCriacaoGrupo)
                    .addComponent(jbConvidarTelaCriarGrupo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTituloGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTituloGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTituloGrupoActionPerformed

    private void jbCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarGrupoActionPerformed
        try {
            ControladorGrupo.getInstance().criarGrupo();        // TODO add your handling code here:
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaCriarGrupo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCriarGrupoActionPerformed

    private void jbCancelarCriacaoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarCriacaoGrupoActionPerformed
        ControladorGrupo.getInstance().fechaTelaCriarGrupo();        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarCriacaoGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarGrupo().setVisible(true);
            }
        });
    }
    public String dadosGrupo() {
        String titulo = new String();
        titulo = tfTituloGrupo.getText();
        return titulo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancelarCriacaoGrupo;
    private javax.swing.JButton jbConvidarTelaCriarGrupo;
    private javax.swing.JButton jbCriarGrupo;
    private java.awt.List listGruposExistentes;
    private javax.swing.JTextField tfTituloGrupo;
    // End of variables declaration//GEN-END:variables

    public void setListaGrupos(){
        listGruposExistentes.removeAll();
        Collection colecao = GrupoDao.getInstance().list();
        ArrayList<Grupo> grupos = new ArrayList<>();
        
        for(Object c : colecao){
            grupos.add((Grupo) c);
        }
        int i;
        int n = grupos.size();
        for(i = 0; i < n; i++){
            listGruposExistentes.add("Titulo: "+grupos.get(i).getTitulo()+" - Aluno Lider: "+grupos.get(i).getAlunoLider().getNome());
        }

    }
}
