/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControladorAtividade;
import dao.AtividadeDao;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Atividade;

/**
 *
 * @author Pizetta
 */
public class TelaListarAtividades extends javax.swing.JFrame {

    /**
     * Creates new form TelaListarAtividades
     */
    public TelaListarAtividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlListarAtividades = new javax.swing.JLabel();
        jbOkListarAtividades = new javax.swing.JButton();
        listaAtividades = new java.awt.List();
        jbAtualizarListaAtividades = new javax.swing.JButton();
        jlIDRemover = new javax.swing.JLabel();
        jtParaRemover = new javax.swing.JTextField();
        jbParaRemover = new javax.swing.JButton();
        jlIDEditar = new javax.swing.JLabel();
        jtParaEditar = new javax.swing.JTextField();
        jbParaEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlListarAtividades.setText("Lista de Atividades:");

        jbOkListarAtividades.setText("Ok");
        jbOkListarAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkListarAtividadesActionPerformed(evt);
            }
        });

        jbAtualizarListaAtividades.setText("Atualizar");
        jbAtualizarListaAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarListaAtividadesActionPerformed(evt);
            }
        });

        jlIDRemover.setText("ID para Remover");

        jbParaRemover.setText("Remover");
        jbParaRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbParaRemoverActionPerformed(evt);
            }
        });

        jlIDEditar.setText("ID para Editar");

        jbParaEditar.setText("Editar");
        jbParaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbParaEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlListarAtividades)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(listaAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbOkListarAtividades)
                                        .addGap(227, 227, 227)
                                        .addComponent(jbAtualizarListaAtividades)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtParaRemover)
                                .addComponent(jlIDRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbParaRemover))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbParaEditar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlIDEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jtParaEditar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlListarAtividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIDRemover)
                    .addComponent(jlIDEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtParaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbParaRemover)
                    .addComponent(jbParaEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOkListarAtividades)
                    .addComponent(jbAtualizarListaAtividades))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkListarAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkListarAtividadesActionPerformed
        ControladorAtividade.getInstance().fechaTelaListarAtividades();
    }//GEN-LAST:event_jbOkListarAtividadesActionPerformed

    private void jbAtualizarListaAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarListaAtividadesActionPerformed
        this.setListaAtividades();
    }//GEN-LAST:event_jbAtualizarListaAtividadesActionPerformed

    private void jbParaRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbParaRemoverActionPerformed
        try {
            ControladorAtividade.getInstance().removerAtividade();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaListarAtividades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbParaRemoverActionPerformed

    private void jbParaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbParaEditarActionPerformed
        ControladorAtividade.getInstance().exibeTelaEditarAtividade();
    }//GEN-LAST:event_jbParaEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarAtividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAtualizarListaAtividades;
    private javax.swing.JButton jbOkListarAtividades;
    private javax.swing.JButton jbParaEditar;
    private javax.swing.JButton jbParaRemover;
    private javax.swing.JLabel jlIDEditar;
    private javax.swing.JLabel jlIDRemover;
    private javax.swing.JLabel jlListarAtividades;
    private javax.swing.JTextField jtParaEditar;
    private javax.swing.JTextField jtParaRemover;
    private java.awt.List listaAtividades;
    // End of variables declaration//GEN-END:variables
     public void setListaAtividades() {
        listaAtividades.removeAll();
        Collection colecao = AtividadeDao.getInstance().list();
        ArrayList<Atividade> atividades = new ArrayList<>();

        for (Object c : colecao) {
            atividades.add((Atividade) c);
        }
        int i;
        int n = atividades.size();
        for (i = 0; i < n; i++) {
            listaAtividades.add("ID: " + atividades.get(i).getAtividadeId()
                    + " - Titulo: " + atividades.get(i).getTitulo()
                    + " - Descricao: " + atividades.get(i).getDescricao()
                    + " - Prazo de Entrega: " + atividades.get(i).getPrazoEntrega()
                    + " - Numero de Participantes: " + atividades.get(i).getNumParticipantes()
            );
        }
    }

    public int idAtividade() {
        String idAtividade = new String();
        idAtividade = jtParaEditar.getText();

        if (!idAtividade.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "ID é um número!");
        }
        return Integer.parseInt(idAtividade);
    }

}
